apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: rest-basic-auth-action
  annotations:
    camel.apache.org/kamelet.support.level: Stable
    camel.apache.org/catalog.version: 4.6.0
    camel.apache.org/kamelet.icon: >-
      data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI0MjAiCmhlaWdodD0iNDIwIiBzdHJva2U9IiMwMDAiIGZpbGw9Im5vbmUiPgo8cGF0aCBzdHJva2Utd2lkdGg9IjI2IgpkPSJNMjA5LDE1YTE5NSwxOTUgMCAxLDAgMiwweiIvPgo8cGF0aCBzdHJva2Utd2lkdGg9IjE4IgpkPSJtMjEwLDE1djM5MG0xOTUtMTk1SDE1TTU5LDkwYTI2MCwyNjAgMCAwLDAgMzAyLDAgbTAsMjQwIGEyNjAsMjYwIDAgMCwwLTMwMiwwTTE5NSwyMGEyNTAsMjUwIDAgMCwwIDAsMzgyIG0zMCwwIGEyNTAsMjUwIDAgMCwwIDAtMzgyIi8+Cjwvc3ZnPg==
    camel.apache.org/provider: Cimetrix
    camel.apache.org/kamelet.group: SMH HTTP Authentication
    camel.apache.org/kamelet.namespace: HTTP Authentication
  labels:
    camel.apache.org/kamelet.type: action
spec:
  definition:
    title: REST Basic Authentication
    description: >-
      Enable REST Basic Authentication for integration REST endpoints. For this
      connector to function properly, REST Basic Authentication add-on needs to
      be enabled for the project. After enabling the REST Basic Authentication
      user credentials need to be added to the 'basic_auth_credentials.conf'
      file, which is created by the add-on.
    required: []
    type: object
    properties: {}
  types:
    in:
      mediaType: ""
    out:
      mediaType: ""
  dependencies:
    - camel:core
    - camel:kamelet
  template:
    route:
      id: route-e3d3
      from:
        id: from-b39f
        uri: kamelet:source
        steps:
          - bean:
              id: bean-5f9e
              ref: restBasicAuthentication
              method: authenticate
              beanType: RestBasicAuthentication
          - log:
              id: log-6229
              message: Request authenticated